name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Gradle DecompileWorkspace
        run: ./gradlew setupDecompWorkspace

      - name: Build File
        run: ./gradlew build
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          files: |
            ./build/libs/**.jar
